### ISSUE TITLE
Remove stale @OptIn annotations for now-stable stdlib APIs

### ISSUE THREAD

**Issue by aminsato** [vultisig/vultisig-android#5897]
## Context
Two stdlib APIs we opt into have been Stable since Kotlin 2.2.0, and the project now compiles on 2.4.20, so their `@OptIn` markers are dead weight:

| Annotation | Gates | Stable since | Files | Annotation lines |
|---|---|---|---|---|
| `ExperimentalEncodingApi` | `kotlin.io.encoding.Base64` | 2.2.0 | 21 | 22 |
| `ExperimentalStdlibApi` | `toHexString` / `hexToByteArray` / `HexFormat` | 2.2.0 | 66 | 72 (+ 2 propagating `@ExperimentalStdlibApi`) |

(80 distinct files — 8 carry both markers on one line.)

## Not in scope: `ExperimentalUuidApi`
`kotlin.uuid.Uuid` is Stable in 2.4.0 for the *compiler*, but stdlib 2.4.20 declares it `@SinceKotlin("2.4") @WasExperimental(ExperimentalUuidApi::class)`. That annotation pair means any analyser running below apiVersion 2.4 still requires the marker — and stable Android Studio (2025.2.x) analyses with a Kotlin 2.2-based frontend, so every `Uuid.random()` call without the opt-in shows as an error in the editor even though Gradle is happy. Keep all `ExperimentalUuidApi` opt-ins (8 files before #5902, 54 after it) until Studio ships a Kotlin ≥ 2.4 frontend.

`Base64` and `HexFormat` carry the same annotation pair at `@SinceKotlin("2.2")`, so removing *their* markers is safe on Studio 2025.2 (Otter) and later, and would show the same editor error on anything older. That is the precondition for this change, and it holds for the team's current Studio versions.

## Change
- Drop `ExperimentalEncodingApi::class` / `ExperimentalStdlibApi::class` from every `@OptIn(...)` / `@file:OptIn(...)`; delete the annotation when nothing is left, keep the remaining markers otherwise (`ExperimentalUuidApi`, `ExperimentalSerializationApi`, `ExperimentalCoroutinesApi`, `ExperimentalMaterial3Api`).
- Remove the two *propagating* `@ExperimentalStdlibApi` annotations (`SendFormViewModel`, `SendFormGraph`). They are the only reason the six `SendFormViewModel*Test` files, `SendFormScreen`, `NavGraph` and `SendFormGraph` opt in without touching a hex API — those fall out once the two annotations go, they are not independent removals.
- Remove the now-unused `import kotlin.io.encoding.ExperimentalEncodingApi` (21 files). `ExperimentalStdlibApi` lives in `kotlin.*` and needs no import.
- Includes `app/src/test`, `data/src/test` and two `app/src/androidTest` files.

## Verification
- `./gradlew assembleDebug :app:compileDebugAndroidTestKotlin :data:compileDebugAndroidTestKotlin` — the compiler is the safety net: any remaining genuinely-experimental call fails with "This declaration needs opt-in". (Every `ExperimentalStdlibApi` use in the codebase is a hex API; the compile confirms there is no other.)
- `./gradlew testDebugUnitTest :app:lintDebug`
- Open the project in Android Studio and confirm no "needs opt-in" errors on Base64 / hex call sites — the Gradle build cannot catch an IDE-frontend mismatch, which is how the `Uuid` case above was found.
- Format with the ktfmt 0.54 CLI: `./gradlew ktfmtFormat` is a silent no-op since #5894 (ktfmt-gradle 0.22.0 only registers tasks when the `kotlin-android` plugin id is applied, which AGP 9's built-in Kotlin never does).

## Reference
https://kotlinlang.org/docs/whatsnew22.html (Base64 / HexFormat Stable) · https://kotlinlang.org/docs/whatsnew24.html (Uuid Stable, with the `@WasExperimental` caveat above)
