### PR TITLE
refactor: kotlin.uuid.Uuid everywhere, drop stale stdlib opt-ins

### LINKED ISSUE #5897: Remove stale @OptIn annotations for now-stable stdlib APIs
## Context
Two stdlib APIs we opt into have been Stable since Kotlin 2.2.0, and the project now compiles on 2.4.20, so their `@OptIn` markers are dead weight:

| Annotation | Gates | Stable since | Files | Annotation lines |
|---|---|---|---|---|
| `ExperimentalEncodingApi` | `kotlin.io.encoding.Base64` | 2.2.0 | 21 | 22 |
| `ExperimentalStdlibApi` | `toHexString` / `hexToByteArray` / `HexFormat` | 2.2.0 | 66 | 72 (+ 2 propagating `@ExperimentalStdlibApi`) |

(80 distinct files — 8 carry both markers on one line.)

## Not in scope: `ExperimentalUuidApi`
`kotlin.uuid.Uuid` is Stable in 2.4.0 for the *compiler*, but stdlib 2.4.20 declares it `@SinceKotlin("2.4") @WasExperimental(ExperimentalUuidApi::class)`. That annotation pair means any analyser running below apiVersion 2.4 still requires the marker — and stable Android Studio (2025.2.x) analyses with a Kotlin 2.2-based frontend, so every `Uuid.random()` call without the opt-in shows as an error in the editor even though Gradle is happy. Keep all `ExperimentalUuidApi` opt-ins (8 files before #5902, 54 after it) until Studio ships a Kotlin ≥ 2.4 frontend.

`Base64` and `HexFormat` carry the same annotation pair at `@SinceKotlin("2.2")`, so removing *their* markers is safe on Studio 2025.2 (Otter) and later, and would show the same editor error on anything older. That is the precondition for this change, and it holds for the team's current Studio versions.

## Change
- Drop `ExperimentalEncodingApi::class` / `ExperimentalStdlibApi::class` from every `@OptIn(...)` / `@file:OptIn(...)`; delete the annotation when nothing is left, keep the remaining markers otherwise (`ExperimentalUuidApi`, `ExperimentalSerializationApi`, `ExperimentalCoroutinesApi`, `ExperimentalMaterial3Api`).
- Remove the two *propagating* `@ExperimentalStdlibApi` annotations (`SendFormViewModel`, `SendFormGraph`). They are the only reason the six `SendFormViewModel*Test` files, `SendFormScreen`, `NavGraph` and `SendFormGraph` opt in without touching a hex API — those fall out once the two annotations go, they are not independent removals.
- Remove the now-unused `import kotlin.io.encoding.ExperimentalEncodingApi` (21 files). `ExperimentalStdlibApi` lives in `kotlin.*` and needs no import.
- Includes `app/src/test`, `data/src/test` and two `app/src/androidTest` files.

## Verification
- `./gradlew assembleDebug :app:compileDebugAndroidTestKotlin :data:compileDebugAndroidTestKotlin` — the compiler is the safety net: any remaining genuinely-experimental call fails with "This declaration needs opt-in". (Every `ExperimentalStdlibApi` use in the codebase is a hex API; the compile confirms there is no other.)
- `./gradlew testDebugUnitTest :app:lintDebug`
- Open the project in Android Studio and confirm no "needs opt-in" errors on Base64 / hex call sites — the Gradle build cannot catch an IDE-frontend mismatch, which is how the `Uuid` case above was found.
- Format with the ktfmt 0.54 CLI: `./gradlew ktfmtFormat` is a silent no-op since #5894 (ktfmt-gradle 0.22.0 only registers tasks when the `kotlin-android` plugin id is applied, which AGP 9's built-in Kotlin never does).

## Reference
https://kotlinlang.org/docs/whatsnew22.html (Base64 / HexFormat Stable) · https://kotlinlang.org/docs/whatsnew24.html (Uuid Stable, with the `@WasExperimental` caveat above)

### LINKED ISSUE #5898: Unify on kotlin.uuid.Uuid instead of java.util.UUID
## Context
`kotlin.uuid.Uuid` became Stable in Kotlin 2.4.0. The codebase is currently split between the two APIs.

## Current state
- 17 files use `kotlin.uuid.Uuid`
- 57 call sites still use `java.util.UUID.randomUUID().toString()`

## Proposed
Replace `UUID.randomUUID().toString()` with `Uuid.random().toString()` across app and data modules. Output format is identical (lowercase hex-and-dash), so persisted IDs and wire formats are unaffected.

## Scope
- `grep -rEn 'UUID\.randomUUID\(\)' app data`
- Keep `java.util.UUID` only where an Android/Java API requires the JVM type (e.g. BLE, WorkManager IDs) — convert with `toJavaUuid()` / `toKotlinUuid()` if needed
- Depends on the stale-`@OptIn` cleanup landing first, or do both together

## Reference
https://kotlinlang.org/docs/whatsnew24.html

### PR DESCRIPTION
**Pull request by aminsato**
Two mechanical Kotlin 2.4 clean-ups, one commit each.

## `kotlin.uuid.Uuid` instead of `java.util.UUID` (#5898)

- Replaces the 57 remaining `java.util.UUID.randomUUID().toString()` sites (46 files) with `kotlin.uuid.Uuid.random().toString()`, so the codebase uses one UUID API. Every site was that exact shape — no `fromString`, no `UUID`-typed fields, no test doubles of `UUID` — so nothing else moves.
- No behaviour change: both produce the same RFC 4122 v4 lowercase hex-and-dash string (checked 1000 samples against the pattern), so persisted vault ids and the session/request ids exchanged with peers are unaffected.
- `@file:OptIn(ExperimentalUuidApi::class)` is kept, matching the 8 files that already used `Uuid` — see below for why.

## Drop `@OptIn` for `Base64` and `HexFormat` (#5897)

- `ExperimentalEncodingApi` and `ExperimentalStdlibApi` have been Stable since Kotlin 2.2.0. Each is removed from its `@OptIn` / `@file:OptIn` list (80 files); the annotation goes when nothing is left, other markers stay.
- The two *propagating* `@ExperimentalStdlibApi` on `SendFormViewModel` and `SendFormGraph` go too — they were the only reason the SendForm tests, `SendFormScreen` and `NavGraph` opted in without touching a hex API.
- Compiling main and androidTest for both modules confirms no removed marker was still required.

## Why `ExperimentalUuidApi` stays

Stdlib 2.4.20 declares `Uuid` as `@SinceKotlin("2.4") @WasExperimental(ExperimentalUuidApi::class)`: stable for a frontend at apiVersion ≥ 2.4, opt-in-only below that. Gradle (2.4.20) is fine, but stable Android Studio (2025.2.x) analyses with a Kotlin 2.2-based frontend and shows "This declaration needs opt-in" on every call without the marker. `Base64` and `HexFormat` carry the same annotation pair at `@SinceKotlin("2.2")`, which that Studio accepts — so those markers can go while the Uuid ones must stay until Studio ships a Kotlin ≥ 2.4 frontend. The compiler emits no warning for the retained opt-ins.

## Test plan

- [x] `./gradlew assembleDebug :app:compileDebugAndroidTestKotlin :data:compileDebugAndroidTestKotlin` — green on the 2.4.20 toolchain
- [x] `./gradlew testDebugUnitTest` — app 2519 / data 3756 tests, 0 failures
- [x] `./gradlew :app:lintDebug` — 0 errors
- [x] ktfmt clean (0.54, run via the CLI — see note below)
- [ ] Open the project in Android Studio and confirm no "needs opt-in" errors on Uuid / Base64 / hex call sites
- [ ] Create a vault / start a keysign on a device and confirm ids still look like `xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx` (sanity only; format is proven above)

Note: since #5894, `./gradlew ktfmtFormat` / `ktfmtCheck` are silent no-ops — ktfmt-gradle 0.22.0 only registers tasks when the `kotlin-android` plugin id is applied, which AGP 9's built-in Kotlin never does. This branch was formatted with the ktfmt 0.54 CLI directly. I'll file that separately.

Closes #5898
Closes #5897

## Summary by CodeRabbit

- **Maintenance**
  - Updated random identifier generation across wallet, transaction, staking, swapping, signing, vault, and session flows.
  - Existing identifier behavior remains unchanged; IDs continue to be generated randomly and used consistently throughout supported operations.
  - Removed unnecessary experimental configuration from application and test code.
  - No user-facing workflow, transaction, signing, validation, or staking behavior changes.

### CODE REVIEW

**Review by johnnyluo — APPROVED** [review]
LGTM
